### ISSUE TITLE
bosh create release fails

### ISSUE THREAD

**Issue by Kaixiang** [18F/newrelic-boshrelease#1]
when we run bosh create release:
it shows error as below:

```
bosh create release
Syncing blobs...
newrelic-daemon/newrelic-sysmond-2.0.3.11... downloading 3.6M (0%)
/opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/blobstore_client-1.2972.0/lib/blobstore_client/simple_blobstore_client.rb:44:in `get_file': Could not fetch object, 403/ (Bosh::Blobstore::BlobstoreError)
    from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/blobstore_client-1.2972.0/lib/blobstore_client/s3_blobstore_client.rb:87:in `get_file'
    from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/blobstore_client-1.2972.0/lib/blobstore_client/base.rb:50:in `get'
    from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/blobstore_client-1.2972.0/lib/blobstore_client/sha1_verifiable_blobstore_client.rb:19:in `get'
    from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/blobstore_client-1.2972.0/lib/blobstore_client/retryable_blobstore_client.rb:19:in `block in get'
    from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/bosh_common-1.2972.0/lib/common/retryable.rb:28:in `call'
    from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/bosh_common-1.2972.0/lib/common/retryable.rb:28:in `block in retryer'
    from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/bosh_common-1.2972.0/lib/common/retryable.rb:26:in `loop'
    from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/bosh_common-1.2972.0/lib/common/retryable.rb:26:in `retryer'
    from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/blobstore_client-1.2972.0/lib/blobstore_client/retryable_blobstore_client.rb:18:in `get'
    from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/bosh_cli-1.2972.0/lib/cli/blob_manager.rb:316:in `download_blob'
    from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/bosh_cli-1.2972.0/lib/cli/blob_manager.rb:242:in `block (3 levels) in process_index'
    from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/bosh_common-1.2972.0/lib/common/thread_pool.rb:77:in `call'
    from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/bosh_common-1.2972.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
    from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/bosh_common-1.2972.0/lib/common/thread_pool.rb:63:in `loop'
    from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/bosh_common-1.2972.0/lib/common/thread_pool.rb:63:in `block in create_thread'
    from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
    from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
```

**Comment by shinji62** [comment]
Seems the s3 bucket access are denied.

**Comment by Kaixiang** [comment]
yep, 
one cent from me is the s3 for blobs should be open to anyone without a private.yml.

**Comment by dlapiduz** [comment]
@Kaixiang Can you check if you can get the blob now? I had many issues settings this up...

**Comment by tushar-dadlani** [comment]
We still cannot access the blobs. We could not create the dev release

**Comment by dlapiduz** [comment]
@tushar-dadlani I am not sure why it is pushing the blobs with the wrong permissions... Can you try again now?

**Comment by shinji62** [comment]
@dlapiduz Maybe you should use the cloudfoundry community blobstore, please ask to @drnic

**Comment by tushar-dadlani** [comment]
@dlapiduz We are still running into the same error.
@shinji62  That sounds like a good idea.

**Comment by drnic** [comment]
Will organize blobstore creds for you

**Comment by dlapiduz** [comment]
Thanks to @drnic I was able to push it to a new bucket. Can you try it now? @Kaixiang @shinji62 @tushar-dadlani

**Comment by Kaixiang** [comment]
hi @dlapiduz  I'm still getting 404 errors as blow

```
Syncing blobs...
newrelic-daemon/newrelic-sysmond-2.0.3.11... downloading 3.6M (0%)
/Users/pivotal/.gem/ruby/2.1.3/gems/blobstore_client-1.2859.0/lib/blobstore_client/simple_blobstore_client.rb:44:in `get_file': Could not fetch object, 404/ (Bosh::Blobstore::BlobstoreError)
    from /Users/pivotal/.gem/ruby/2.1.3/gems/blobstore_client-1.2859.0/lib/blobstore_client/s3_blobstore_client.rb:87:in `get_file'
    from /Users/pivotal/.gem/ruby/2.1.3/gems/blobstore_client-1.2859.0/lib/blobstore_client/base.rb:50:in `get'
    from /Users/pivotal/.gem/ruby/2.1.3/gems/blobstore_client-1.2859.0/lib/blobstore_client/sha1_verifiable_blobstore_client.rb:19:in `get'
    from /Users/pivotal/.gem/ruby/2.1.3/gems/blobstore_client-1.2859.0/lib/blobstore_client/retryable_blobstore_client.rb:19:in `block in get'
    from /Users/pivotal/.gem/ruby/2.1.3/gems/bosh_common-1.2859.0/lib/common/retryable.rb:28:in `call'
    from /Users/pivotal/.gem/ruby/2.1.3/gems/bosh_common-1.2859.0/lib/common/retryable.rb:28:in `block in retryer'
    from /Users/pivotal/.gem/ruby/2.1.3/gems/bosh_common-1.2859.0/lib/common/retryable.rb:26:in `loop'
    from /Users/pivotal/.gem/ruby/2.1.3/gems/bosh_common-1.2859.0/lib/common/retryable.rb:26:in `retryer'
    from /Users/pivotal/.gem/ruby/2.1.3/gems/blobstore_client-1.2859.0/lib/blobstore_client/retryable_blobstore_client.rb:18:in `get'
    from /Users/pivotal/.gem/ruby/2.1.3/gems/bosh_cli-1.2859.0/lib/cli/blob_manager.rb:316:in `download_blob'
    from /Users/pivotal/.gem/ruby/2.1.3/gems/bosh_cli-1.2859.0/lib/cli/blob_manager.rb:242:in `block (3 levels) in process_index'
    from /Users/pivotal/.gem/ruby/2.1.3/gems/bosh_common-1.2859.0/lib/common/thread_pool.rb:77:in `call'
    from /Users/pivotal/.gem/ruby/2.1.3/gems/bosh_common-1.2859.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
    from /Users/pivotal/.gem/ruby/2.1.3/gems/bosh_common-1.2859.0/lib/common/thread_pool.rb:63:in `loop'
    from /Users/pivotal/.gem/ruby/2.1.3/gems/bosh_common-1.2859.0/lib/common/thread_pool.rb:63:in `block in create_thread'
    from /Users/pivotal/.gem/ruby/2.1.3/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
    from /Users/pivotal/.gem/ruby/2.1.3/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
```

**Comment by dlapiduz** [comment]
@Kaixiang sorry, I pushed it to my fork instead of the community one. Can you try again?

**Comment by Kaixiang** [comment]
hi @dlapiduz, it works for the newrelic blob but now we see some errors like below for the license:

```
bosh create release

Syncing blobs...
newrelic-daemon/newrelic-sysmond-2.0.3.11... downloaded
Please enter development release name: newrelic-boshrelease

Building DEV release
---------------------------------
Release artifact cache: /Users/pivotal/.bosh/cache

Building license
----------------
Building license...
  Using final version 'f26fbb8045186235ed661742128b0b5c4a4fb22b'
  Downloading from blobstore (id=a810be34-b1fb-44d6-9390-8fb1bf765e20)...
Blobstore error: Could not fetch object, 403/

```

**Comment by dlapiduz** [comment]
@Kaixiang hmmm there shouldn't be a blob object for the license...

I tried it locally on a fresh clone and it seems to work. Can you try it with a new clone? Are you just running `bosh create release`?

**Comment by tushar-dadlani** [comment]
@dlapiduz , we tried it with a new clone and the issue still exists.

We are using BOSH 1.2977.0

**Comment by dlapiduz** [comment]
@tushar-dadlani @Kaixiang are you still having issues? I tried reaching out through email a bit over a week ago without any luck...

**Comment by tushar-dadlani** [comment]
@dlapiduz  We are still facing the issue to create a dev release. There are some bucket/blobstore permission issues at your end. 

```
 bosh create release
Syncing blobs...
newrelic-daemon/newrelic-sysmond-2.0.3.11... downloaded
Please enter development release name: newrelic-boshrelease

Building DEV release
---------------------------------

Building packages
-----------------
Building newrelic-daemon...
  Using final version
  Downloading from blobstore (id=cc5cb811-af15-4651-8dfe-977b818f68c0)...
Blobstore error: Could not fetch object, 403/

```

**Comment by dlapiduz** [comment]
@tushar-dadlani @Kaixiang I finally found the issue. I wasn't able to replicate it before because bosh had cached the packages in both my local box and my production environment.

Basically there were a bunch of blobs that were never uploaded and that was causing issues. Please try again now...

**Comment by dlapiduz** [comment]
And my apologies for the newbienes managing a bosh release!

**Comment by tushar-dadlani** [comment]
@dlapiduz  It works now. Thanks
